/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wsmo.wsml.compiler.lexer;

public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
